apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "js-ipfs.fullname" . }}-ipfs-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "js-ipfs.name" . }}
    helm.sh/chart: {{ include "js-ipfs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config: | {{ toJson .Values.ipfs.config  | nindent 4 }}
