apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "js-ipfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "js-ipfs.name" . }}
    helm.sh/chart: {{ include "js-ipfs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "js-ipfs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "js-ipfs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: js-ipfs
          image: "{{ .Values.ipfs.image.repository }}:{{ .Values.ipfs.image.tag }}"
          ports:
            - name: ipfs-swarm
              containerPort: 4002
            - name: ipfs-api
              containerPort: 5002
          readinessProbe:
            httpGet:
              path: /api/v0/id
              port: ipfs-api
            initialDelaySeconds: {{ .Values.ipfs.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ipfs.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ipfs.readinessProbe.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /api/v0/id
              port: ipfs-api
            initialDelaySeconds: {{ .Values.ipfs.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.ipfs.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.ipfs.livenessProbe.timeoutSeconds }}
          env:
            - name: IPFS_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "js-ipfs.fullname" . }}-ipfs-config
                  key: config
            {{- toYaml .Values.ipfs.env | nindent 12 }}
          resources:
            {{- toYaml .Values.ipfs.resources | nindent 12 }}
          volumeMounts:
            - name: ipfs-config
              mountPath: /root/.jsipfs
      volumes:
        - name: ipfs-config
          emptyDir: {}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
