apiVersion: v1
kind: Service
metadata:
  name: {{ include "js-ipfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "js-ipfs.name" . }}
    helm.sh/chart: {{ include "js-ipfs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "js-ipfs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: swarm
      protocol: TCP
      port: {{ .Values.service.swarm.port }}
      targetPort: ipfs-swarm
    - name: ipfs-api
      protocol: TCP
      port: {{ .Values.service.ipfsAPI.port }}
      targetPort: ipfs-api
