# Default values for ipfs-testbed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

toxiproxy:
  image:
    repository: shopify/toxiproxy
    tag: latest
    pullPolicy: IfNotPresent
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 1
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 1
  config:
    - name: "ipfs_swarm"
      listen: "0.0.0.0:8002"
      upstream: "0.0.0.0:4002"

ipfs:
  image:
    repository: registry.gitlab.com/johnytiago/js-ipfs
    tag: latest
    pullPolicy: IfNotPresent
  env:
    - name: "DEBUG"
      value: "libp2p:startrail*,libp2p:dht*,jsipfs*"
    - name: "IPFS_KUBERNETES_PROXY"
      value: "true"
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 3
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 3
  config:
    Addresses:
      API: "/ip4/0.0.0.0/tcp/5002"
      Swarm:
        - "/ip4/127.0.0.1/tcp/4002"
    Discovery:
      MDNS:
        Enabled: false
      webRTCStar:
        Enabled: true
    Bootstrap: []

nameOverride: ""
fullnameOverride: ""
service:
  type: NodePort
  swarm:
    port: 8002
  toxiproxyAPI:
    port: 8474
  ipfsAPI:
    port: 5002

dataset: 
 url: "minikube" # OR "https://startrail.joaotiago.dev.s3.amazonaws.com/dataset-1.tar.gz"
 test_endpoint: "/api/v0/cat?arg=/ipfs/QmdA5WkDNALetBn4iFeSepHjdLGJdxPBwZyY47ir1bZGAK/home.html"

nodeSelector: {}

tolerations: []

affinity: {}
